/**
 * This class is generated by jOOQ
 */
package jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_2276EFF0_4858_4855_B0A8_49169FEBA33F</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_2276EFF0_4858_4855_B0A8_49169FEBA33F = new SequenceImpl<Long>("SYSTEM_SEQUENCE_2276EFF0_4858_4855_B0A8_49169FEBA33F", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
